import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            // {
            //     key: 'apps.project',
            //     path: '',
            //     title: 'Project',
            //     translateKey: 'nav.appsProject.project',
            //     icon: 'project',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsProject.dashboard',
            //             path: `${APP_PREFIX_PATH}/project/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsProject.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.projectList',
            //             path: `${APP_PREFIX_PATH}/project/project-list`,
            //             title: 'Project List',
            //             translateKey: 'nav.appsProject.projectList',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.scrumBoard',
            //             path: `${APP_PREFIX_PATH}/project/scrum-board`,
            //             title: 'Scrum Board',
            //             translateKey: 'nav.appsProject.scrumBoard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.issue',
            //             path: `${APP_PREFIX_PATH}/project/issue`,
            //             title: 'Issue',
            //             translateKey: 'nav.appsProject.issue',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.crm',
            //     path: '',
            //     title: 'CRM',
            //     translateKey: 'nav.appsCrm.crm',
            //     icon: 'crm',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsCrm.dashboard',
            //             path: `${APP_PREFIX_PATH}/crm/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsCrm.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrm.calendar',
            //             path: `${APP_PREFIX_PATH}/crm/calendar`,
            //             title: 'Calendar',
            //             translateKey: 'nav.appsCrm.calendar',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrm.customers',
            //             path: `${APP_PREFIX_PATH}/crm/customers`,
            //             title: 'Customers',
            //             translateKey: 'nav.appsCrm.customers',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrm.customerDetails',
            //             path: `${APP_PREFIX_PATH}/crm/customer-details?id=8`,
            //             title: 'Customer Details',
            //             translateKey: 'nav.appsCrm.customerDetails',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrm.mail',
            //             path: `${APP_PREFIX_PATH}/crm/mail`,
            //             title: 'Mail',
            //             translateKey: 'nav.appsCrm.mail',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            {
                key: 'apps.products',
                path: '',
                title: 'Products',
                translateKey: 'nav.appsProducts.products',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsSalesV2.productList',
                        path: `${APP_PREFIX_PATH}/sales-v2/product-list`,
                        title: 'Products',
                        translateKey: 'nav.appsSales.productListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsSalesV2.productNew',
                        path: `${APP_PREFIX_PATH}/sales-v2/product-new`,
                        title: 'New Product',
                        translateKey: 'nav.appsSales.productNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.vendors',
                path: '',
                title: 'Vendors',
                translateKey: 'nav.appsVendors.vendors',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsVendorsV2.vendorList',
                        path: `${APP_PREFIX_PATH}/vendors-v2/vendor-list`,
                        title: 'Vendors',
                        translateKey: 'nav.appsVendors.vendorListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsVendorsV2.new',
                        path: `${APP_PREFIX_PATH}/vendors-v2/vendor-new`,
                        title: 'New Vendor',
                        translateKey: 'nav.appsVendors.vendorNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.categories',
                path: '',
                title: 'Categories',
                translateKey: 'nav.appsCategories.categories',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsCategoriesV2.categoryList',
                        path: `${APP_PREFIX_PATH}/categories-v2/category-list`,
                        title: 'Categories',
                        translateKey: 'nav.appsCategories.categoryListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCategoriesV2.categoryNew',
                        path: `${APP_PREFIX_PATH}/categories-v2/category-new`,
                        title: 'New Category',
                        translateKey: 'nav.appsCategories.categoryNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.purohits',
                path: '',
                title: 'Purohits',
                translateKey: 'nav.appsPurohits.purohits',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsPurohitsV2.list',
                        path: `${APP_PREFIX_PATH}/purohits-v2/purohit-list`,
                        title: 'Purohits',
                        translateKey: 'nav.appsPurohits.purohitsListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsPurohitsV2.new',
                        path: `${APP_PREFIX_PATH}/purohits-v2/purohit-new`,
                        title: 'New Purohit',
                        translateKey: 'nav.appsPurohits.purohitNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.events',
                path: '',
                title: 'Events',
                translateKey: 'nav.appsEvents.events',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsEventsV2.list',
                        path: `${APP_PREFIX_PATH}/events-v2/event-list`,
                        title: 'Events',
                        translateKey: 'nav.appsEvents.eventsListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsEventsV2.new',
                        path: `${APP_PREFIX_PATH}/events-v2/event-new`,
                        title: 'New Event',
                        translateKey: 'nav.appsEvents.eventNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.promos',
                path: '',
                title: 'Promos',
                translateKey: 'nav.appsPromos.promos',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsPromosV2.list',
                        path: `${APP_PREFIX_PATH}/promos-v2/promo-list`,
                        title: 'Promos',
                        translateKey: 'nav.appsPromos.promosListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsPromosV2.new',
                        path: `${APP_PREFIX_PATH}/promos-v2/promo-new`,
                        title: 'New Promo',
                        translateKey: 'nav.appsPromos.promoNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.offers',
                path: '',
                title: 'Offers',
                translateKey: 'nav.appsOffers.offers',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsOffersV2.list',
                        path: `${APP_PREFIX_PATH}/offers-v2/offer-list`,
                        title: 'Offers',
                        translateKey: 'nav.appsOffers.offersListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsOffersV2.new',
                        path: `${APP_PREFIX_PATH}/offers-v2/offer-new`,
                        title: 'New Offer',
                        translateKey: 'nav.appsOffers.offerNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.homepage',
                path: '',
                title: 'Homepage',
                translateKey: 'nav.appsHomepage.homepage',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsHomepageV2.configure',
                        path: `${APP_PREFIX_PATH}/homepage-v2/configure`,
                        title: 'Homepage Configure',
                        translateKey: 'nav.appsHomepage.configureV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.bookings',
                path: '',
                title: 'Bookings',
                translateKey: 'nav.appsBookings.bookings',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsBookingsV2.list',
                        path: `${APP_PREFIX_PATH}/bookings-v2/booking-list`,
                        title: 'Bookings',
                        translateKey: 'nav.appsBookings.bookingsListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsBookingsV2.new',
                        path: `${APP_PREFIX_PATH}/bookings-v2/booking-new`,
                        title: 'New Booking',
                        translateKey: 'nav.appsBookings.bookingNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.payments',
                path: '',
                title: 'Payments',
                translateKey: 'nav.appsPayments.payments',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsPaymentsV2.list',
                        path: `${APP_PREFIX_PATH}/payments-v2/payment-list`,
                        title: 'Payments',
                        translateKey: 'nav.appsPayments.paymentsListV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsPaymentsV2.new',
                        path: `${APP_PREFIX_PATH}/payments-v2/payment-new`,
                        title: 'New Payment',
                        translateKey: 'nav.appsPayments.paymentNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.delivery',
                path: '',
                title: 'Delivery',
                translateKey: 'nav.appsDelivery.delivery',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsDeliverySlotsV2.create',
                        path: `${APP_PREFIX_PATH}/delivery-v2/slot-new`,
                        title: 'New Slot',
                        translateKey: 'nav.appsDelivery.slotNewV2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            // {
            //     key: 'apps.crypto',
            //     path: '',
            //     title: 'Crypto',
            //     translateKey: 'nav.appsCrypto.crypto',
            //     icon: 'crypto',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsCrypto.dashboard',
            //             path: `${APP_PREFIX_PATH}/crypto/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsCrypto.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.portfolio',
            //             path: `${APP_PREFIX_PATH}/crypto/portfolio`,
            //             title: 'Portfolio',
            //             translateKey: 'nav.appsCrypto.portfolio',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.market',
            //             path: `${APP_PREFIX_PATH}/crypto/market`,
            //             title: 'Market',
            //             translateKey: 'nav.appsCrypto.market',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.wallets',
            //             path: `${APP_PREFIX_PATH}/crypto/wallets`,
            //             title: 'Wallets',
            //             translateKey: 'nav.appsCrypto.wallets',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.knowledgeBase',
            //     path: '',
            //     title: 'Knowledge Base',
            //     translateKey: 'nav.appsknowledgeBase.knowledgeBase',
            //     icon: 'knowledgeBase',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsknowledgeBase.helpCenter',
            //             path: `${APP_PREFIX_PATH}/knowledge-base/help-center`,
            //             title: 'Help Center',
            //             translateKey: 'nav.appsknowledgeBase.helpCenter',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsknowledgeBase.article',
            //             path: `${APP_PREFIX_PATH}/knowledge-base/article?id=rZjCbSyae5`,
            //             title: 'Article',
            //             translateKey: 'nav.appsknowledgeBase.article',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsknowledgeBase.manageArticles',
            //             path: `${APP_PREFIX_PATH}/knowledge-base/manage-articles`,
            //             title: 'Manage Articles',
            //             translateKey: 'nav.appsknowledgeBase.manageArticles',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsknowledgeBase.editArticle',
            //             path: `${APP_PREFIX_PATH}/knowledge-base/edit-article?id=rZjCbSyae5&categoryLabel=Survey&categoryValue=survey`,
            //             title: 'Edit Article',
            //             translateKey: 'nav.appsknowledgeBase.editArticle',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.account',
            //     path: '',
            //     title: 'Account',
            //     translateKey: 'nav.appsAccount.account',
            //     icon: 'account',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsAccount.settings',
            //             path: `${APP_PREFIX_PATH}/account/settings/profile`,
            //             title: 'Settings',
            //             translateKey: 'nav.appsAccount.settings',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.invoice',
            //             path: `${APP_PREFIX_PATH}/account/invoice/36223`,
            //             title: 'Invoice',
            //             translateKey: 'nav.appsAccount.invoice',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.activityLog',
            //             path: `${APP_PREFIX_PATH}/account/activity-log`,
            //             title: 'Activity Log',
            //             translateKey: 'nav.appsAccount.activityLog',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.kycForm',
            //             path: `${APP_PREFIX_PATH}/account/kyc-form`,
            //             title: 'KYC Form',
            //             translateKey: 'nav.appsAccount.kycForm',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
        ],
    },
]

export default appsNavigationConfig
